config/routes.rb
Rails.application.routes.draw do
  # root to: "landing#show"

  namespace :my do
    root to: "dashboard#show"

    # resource :account, only: [:show, :edit, :update]
  end

  namespace :manage do
    root to: "dashboard#show"

    resource :profile, only: [:show, :new, :create, :edit, :update]

    resources :beneficiaries, only: [:index, :show, :new, :create, :edit, :update] do
      resources :needs, only: [:new, :create, :edit, :update]
    end

    resources :donors, only: [:index, :show]

    resources :campaigns, only: [:index, :show, :new, :create, :edit, :update] do
      # put :show
      # put :hide

      scope module: "campaigns" do
        # resource :launch, only: [:show, :create]
        # resource :archive, only: [:show, :create]

        # resource :need, only: [:show, :new, :create, :destroy]
        # resource :pool, only: [:show, :new, :create, :destroy]

        resources :updates, only: [:new, :create, :edit, :update, :destroy]
      end
    end

    resources :pools, only: [:index, :show] do
      resources :disbursements, only: [:new, :create]
    end
  end

  namespace :coordinate do
    root to: "dashboard#show"

    resource :profile, only: [:show, :new, :create, :edit, :update]

    resource :pool, only: [:show, :new, :create, :destroy]

    resources :donations, only: [:index, :show, :new, :create]
  end

  namespace :admin do
    root to: "dashboard#show"

    resources :labels, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :accounts, only: [:index, :show] do
      # put :activate, on: :member
      # put :deactivate, on: :member
    end

    # TODO: improve onboarding experience for managers
    # resources :managers, only: [:index, :new, :create, :destroy]

    # resources :coordinators, only: [:index] do
    #   put :approve, on: :member
    #   put :deny, on: :member
    # end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model

  enum :status, unverified: 1, verified: 2, closed: 3

  has_many :profiles

  validates :email, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one :profile, as: :profileable, required: true

  delegate :display_name, to: :profile

  accepts_nested_attributes_for :profile, update_only: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
  has_many :needs

  enum gender: {
    male: "male",
    female: "female",
  }

  validates :full_name, presence: true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :manager
  belongs_to :need, optional: true
  belongs_to :pool, optional: true

  has_many :updates

  validates :funding_goal, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :title, :description, :start_date, :end_date, presence: true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :beneficiary
  belongs_to :manager

  validates :nature, presence: true
end

app/models/contact_method.rb
class ContactMethod
  include ActiveModel::Model

  attr_accessor :type, :value

  validates :type, :value, presence: true
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  has_one :profile, as: :profileable, required: true
  has_many :pools, as: :handler

  validate :at_least_one_contact_method

  accepts_nested_attributes_for :profile, update_only: true

  delegate :display_name, to: :profile

  def contact_methods
    super.map { |params| ContactMethod.new(params) }
  end

  def contact_methods_attributes=(params)
    self.contact_methods = params.map { |_, values| ContactMethod.new(values) }
  end

  private

  def at_least_one_contact_method
    errors.add(:contact_methods, "At least one contact method") if contact_methods.empty?
  end
end

app/models/disbursement.rb
class Disbursement < ApplicationRecord
  has_one :transaction_record, as: :transactable, required: true
  accepts_nested_attributes_for :transaction_record

  has_one :pool, through: :transaction_record

  belongs_to :need
end

app/models/donation.rb
class Donation < ApplicationRecord
  has_one :transaction_record, as: :transactable, required: true
  accepts_nested_attributes_for :transaction_record

  has_one :pool, through: :transaction_record

  belongs_to :donor
  accepts_nested_attributes_for :donor
end

app/models/donor.rb
class Donor < ApplicationRecord
  has_many :donations

  validates :name, presence: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :needs

  validates :name, presence: true
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_one :profile, as: :profileable, required: true

  has_many :campaigns
  has_many :needs
  has_many :updates

  validates :contact_number, presence: true

  accepts_nested_attributes_for :profile, update_only: true

  delegate :display_name, to: :profile
end

app/models/need.rb
class Need < ApplicationRecord
  belongs_to :beneficiary
  belongs_to :manager
  belongs_to :label

  has_many :disbursements

  validates :description, presence: true
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :handler, polymorphic: true

  has_many :transaction_records

  enum status: {
    active: "active",
    inactive: "inactive",
  }

  validates :name, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  delegated_type :profileable, types: %w[Admin Manager Coordinator], dependent: :destroy

  belongs_to :account

  validates :display_name, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  delegated_type :transactable, types: %w[Disbursement Donation], dependent: :destroy

  belongs_to :pool

  validates :value, presence: true, numericality: { only_integer: true }
end

app/models/transaction_record.rb
class TransactionRecord < ApplicationRecord
  delegated_type :transactable, types: %w[Disbursement Donation], dependent: :destroy

  belongs_to :pool

  validates :value, presence: true, numericality: { only_integer: true }
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :campaign
  belongs_to :manager

  validates :body, presence: true
end

app/controllers/admin/labels_controller.rb
class Admin::LabelsController < Admin::BaseController
  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to [:admin, :labels], status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @label = Label.find(params[:id])
  end

  def update
    @label = Label.find(params[:id])
    if @label.update(label_params)
      redirect_to [:admin, :labels], status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy!
    redirect_to [:admin, :labels], status: :see_other
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers
  layout "guest"
end

app/helpers/application_helper.rb
module ApplicationHelper
  def input_class(error: false)
    base = "block w-full appearance-none rounded-md border sm:text-sm"
    if error
      "#{base} border-red-300 pr-10 text-red-900 placeholder-red-300 focus:border-red-500 focus:outline-none focus:ring-red-500"
    else
      "#{base} border-gray-300 px-3 py-2 placeholder-gray-400 shadow-sm focus:border-green-500 focus:outline-none focus:ring-green-500"
    end
  end
end

app/views/admin/labels/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <!--
      Background backdrop, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
        <!--
          Modal panel, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            To: "opacity-100 translate-y-0 sm:scale-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100 translate-y-0 sm:scale-100"
            To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        -->
        <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6">
          <%= simple_form_for [:admin, @label], data: { turbo_frame: :admin_labels } do |form| %>
            <div class="mt-3 text-center sm:mt-5">
              <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">Edit Label</h3>
            </div>

            <div class="sm:col-span-6">
              <%= form.input :name, label: false, input: false do %>
                <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1">
                  <%= form.input_field :name, class: input_class(error: form.object.errors[:name].present?) %>
                </div>
              <%- end %>
            </div>

            <div class="mt-5 sm:mt-6">
              <%= form.submit "Save Changes", class: "inline-flex w-full justify-center rounded-md border border-transparent bg-green-600 py-3 px-4 text-sm font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2" %>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
<%- end %>

app/views/admin/labels/index.html.erb
<%= turbo_stream.replace :header_title do %>
  <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">Labels</h2>
<%- end %>

<%= turbo_frame_tag :admin_labels do %>

  <%= render partial: "modal_reset" %>

  <div class="container mx-auto">

    <div class="px-4 sm:px-6 lg:px-12">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">

        </div>

        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to "Add Label", new_admin_label_path, data: { turbo_frame: :modal }, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-green-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 sm:w-auto" %>
        </div>
      </div>

      <div class="mt-8 overflow-hidden bg-white sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
              <table class="min-w-full divide-y divide-gray-300">

                <thead>
                  <tr>
                    <th scope="col" class="py-8 pl-4 px-3 text-left text-sm font-normal text-gray-500 sm:pl-6">Name</th>
                    <th scope="col" class="py-8 pl-4 px-3 text-left text-sm font-normal text-gray-500 sm:pl-6"></th>
                  </tr>
                </thead>

                <tbody class="divide-y divide-gray-200">
                  <%- @labels.each do |label| %>
                    <tr>
                      <td class="whitespace-nowrap py-8 pl-4 px-3 text-sm font-medium text-gray-900 sm:pl-6">
                        <%= link_to label.name, [:edit, :admin, label], data: { turbo_frame: :modal } %>
                      </td>
                      <td class="whitespace-nowrap py-8 pl-4 px-3 text-sm font-medium text-gray-900 sm:pl-6">
                        <%= link_to "Delete", [:admin, label], data: { turbo_method: :delete } %>
                      </td>
                    </tr>
                  <%- end %>
                </tbody>

              </table>
            </div>
          </div>
        </div>
        </div>
      </div>

    </div>

  </div>
<%- end %>

app/views/admin/labels/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <!--
      Background backdrop, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
        <!--
          Modal panel, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            To: "opacity-100 translate-y-0 sm:scale-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100 translate-y-0 sm:scale-100"
            To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        -->
        <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6">
          <%= simple_form_for [:admin, @label], data: { turbo_frame: :admin_labels } do |form| %>
            <div class="mt-3 text-center sm:mt-5">
              <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">Add Label</h3>
            </div>

            <div class="sm:col-span-6">
              <%= form.input :name, label: false, input: false do %>
                <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1">
                  <%= form.input_field :name, class: input_class(error: form.object.errors[:name].present?) %>
                </div>
              <%- end %>
            </div>

            <div class="mt-5 sm:mt-6">
              <%= form.submit "Add Label", class: "inline-flex w-full justify-center rounded-md border border-transparent bg-green-600 py-3 px-4 text-sm font-medium text-white shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2" %>
            </div>
          <%- end %>
        </div>
      </div>
    </div>
  </div>
<%- end %>